[project]
name = "seqeval"
version = "1.2.3"
dynamic = ["description", "readme"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
